**Problem 1**
You as the part of project have to explore, analyze and treat the data for the below mentioned

1)  number of columns in each dataset
2)  duplicate rows in each dataset
3)  datatypes of columns
4)  features with missing values
5)  number of non-null unique values for features in each dataset
6)  what those unique values are and counts for each

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [12]:
from google.colab import drive
import pandas as pd
drive.mount('/content/drive', force_remount=True)


# Load Excel files
df1 = pd.read_excel('/content/drive/MyDrive/capstone project infosys/all_alpha_08.xlsx' )
df2 = pd.read_excel('/content/drive/MyDrive/capstone project infosys/all_alpha_09.xls')
df3 = pd.read_excel('/content/drive/MyDrive/capstone project infosys/all_alpha_10.xls')
df4 = pd.read_excel('/content/drive/MyDrive/capstone project infosys/all_alpha_11.xlsx')
df5 = pd.read_excel('/content/drive/MyDrive/capstone project infosys/all_alpha_12.xlsx')
df6 = pd.read_excel('/content/drive/MyDrive/capstone project infosys/all_alpha_13.xlsx')
df7 = pd.read_excel('/content/drive/MyDrive/capstone project infosys/all_alpha_14.xlsx')
df8 = pd.read_excel('/content/drive/MyDrive/capstone project infosys/all_alpha_15.xlsx')
df9 = pd.read_excel('/content/drive/MyDrive/capstone project infosys/all_alpha_16.xlsx')
df10 = pd.read_excel('/content/drive/MyDrive/capstone project infosys/all_alpha_17.xlsx')
df11= pd.read_excel('/content/drive/MyDrive/capstone project infosys/all_alpha_18.xlsx')
combined_df = pd.concat([df1, df2, df3,df4,df5,df6,df7,df8,df9,df10,df11], axis=0)
combined_df = pd.concat([df1, df2, df3,df4,df5,df6,df7,df8,df9,df10,df11], axis=1)
# Save to Excel
combined_df.to_excel('/content/Newdata.xlsx', index=False)

# Save to CSV
combined_df.to_csv('/content/Newdata.csv', index=False)

Mounted at /content/drive

In [13]:

df = pd.read_csv('/content/Newdata.csv')
df.head()

,Model,Displ,Cyl,Trans,Drive,Fuel,Sales Area,Stnd,Underhood ID,Veh Class,...,Stnd Description.9,Underhood ID.10,Veh Class.10,Air Pollution Score.10,City MPG.10,Hwy MPG.10,Cmb MPG.10,Greenhouse Gas Score.10,SmartWay.10,Comb CO2.5
0,ACURA MDX,3.7,(6 cyl),Auto-S5,4WD,Gasoline,CA,U2,8HNXT03.7PKR,SUV,...,California LEV-III ULEV125,JHNXV02.4NH3,small car,3,25,35,29,6,No,309
1,ACURA MDX,3.7,(6 cyl),Auto-S5,4WD,Gasoline,FA,B5,8HNXT03.7PKR,SUV,...,Federal Tier 3 Bin 125,JHNXV02.4NH3,small car,3,25,35,29,6,No,309
2,ACURA RDX,2.3,(4 cyl),Auto-S5,4WD,Gasoline,CA,U2,8HNXT02.3DKR,SUV,...,California LEV-III ULEV125,JHNXV03.08H3,small SUV,3,26,27,27,6,No,330
3,ACURA RDX,2.3,(4 cyl),Auto-S5,4WD,Gasoline,FA,B5,8HNXT02.3DKR,SUV,...,Federal Tier 3 Bin 125,JHNXV03.08H3,small SUV,3,26,27,27,6,No,330
4,ACURA RL,3.5,(6 cyl),Auto-S5,4WD,Gasoline,CA,U2,8HNXV03.5HKR,midsize car,...,California LEV-III ULEV125,JHNXV03.5RH3,small SUV,3,19,27,22,4,No,404

In [14]:
## [1]to show the total no. of columns in each data set in the combined data set(Newdata)

unique_columns = df.columns.unique()
print(unique_columns)

Index(['Model', 'Displ', 'Cyl', 'Trans', 'Drive', 'Fuel', 'Sales Area', 'Stnd',
       'Underhood ID', 'Veh Class',
       ...
       'Stnd Description.9', 'Underhood ID.10', 'Veh Class.10',
       'Air Pollution Score.10', 'City MPG.10', 'Hwy MPG.10', 'Cmb MPG.10',
       'Greenhouse Gas Score.10', 'SmartWay.10', 'Comb CO2.5'],
      dtype='object', length=194)

In [18]:
## [2]duplicate rows in each dataset

duplicates_df = df[df.duplicated()]
num_duplicates_df = duplicates_df.shape[0]
print(f"Number of duplicate rows in the dataset: {num_duplicates_df}")

Number of duplicate rows in the dataset: 0

In [19]:
## [3]datatypes of columns

data_typescol = df.dtypes[unique_columns]
print("Data types of unique columns:")
print(data_typescol)

Data types of unique columns:
Model                       object
Displ                      float64
Cyl                         object
Trans                       object
Drive                       object
                            ...
Hwy MPG.10                  object
Cmb MPG.10                  object
Greenhouse Gas Score.10      int64
SmartWay.10                 object
Comb CO2.5                  object
Length: 194, dtype: object

In [20]:
## [4]features with missing values

missing_values = df.isnull().sum()

# Filtering out columns with no missing values
missing_values = missing_values[missing_values > 0]
print("Features with missing values:")
print(missing_values)

Features with missing values:
Model                     309
Displ                     309
Cyl                       508
Trans                     508
Drive                     402
                         ...
Greenhouse Gas Score.9    124
SmartWay.9                124
Comb CO2.4                124
Displ.10                   50
Cyl.10                     50
Length: 178, dtype: int64

In [21]:
##[5]number of non-null unique values for features in each dataset



# Function to count non-null unique values for each column in a the DataFrame df
def count_nonnull(df):
    non_nullcounts = df.apply(lambda x: x.dropna().nunique())
    return non_nullcounts

# Count non-null unique values for the dataset
non_nullcounts_df = count_nonnull(df)

print("Number of non-null unique values in the dataset:")
print(non_nullcounts_df)

Number of non-null unique values in the dataset:
Model                      436
Displ                       47
Cyl                          8
Trans                       14
Drive                        2
                          ...
Hwy MPG.10                 119
Cmb MPG.10                 110
Greenhouse Gas Score.10     10
SmartWay.10                  3
Comb CO2.5                 404
Length: 194, dtype: int64

In [23]:
##[6]what those unique values are and counts for each


# Function to count unique values and their occurrences for each column in DataFrame df
def unique_values_counts(df):
    unique_counts_dict = {}
    for column in df.columns:
        unique_counts_dict[column] = df[column].value_counts(dropna=True)
    return unique_counts_dict

unique_counts_df = unique_values_counts(df)

def display_unique_counts(unique_counts_dict, dataset_name):
    print(f"Unique values and their counts in {dataset_name}:")
    for column, counts in unique_counts_dict.items():
        print(f"\nColumn: {column}")
        print(counts)

display_unique_counts(unique_counts_df, "the first dataset")

Unique values and their counts in the first dataset:

Column: Model
Model
GMC Sierra 15                     25
FORD Ranger                       24
FORD F350                         22
HONDA Accord                      22
DODGE RAM 1500                    21
                                  ..
MERCEDES-BENZ C350                 1
MERCEDES-BENZ E320 Bluetec         1
MERCEDES-BENZ CLS550               1
MERCEDES-BENZ CLK350               1
MERCEDES-BENZ CLK350 Cabriolet     1
Name: count, Length: 436, dtype: int64

Column: Displ
Displ
3.5    194
2.4    184
2.5    171
3.0    158
2.0    132
3.6    110
5.3    108
6.0    103
3.7     86
5.4     81
4.0     80
4.6     80
4.8     74
2.3     71
2.7     68
3.8     62
5.7     59
4.2     57
4.7     45
6.2     41
1.8     36
3.2     34
5.5     30
2.2     30
5.0     29
1.6     24
2.9     24
3.3     24
4.3     22
5.6     20
3.1     18
4.4     16
3.4     16
6.7     14
6.8     13
1.5     12
2.8     12
5.9     12
6.1     12
6.5     10
3.9      8
1.3      6
4.5      6
8.4      4
5.2      4
7.0      2
8.0      2
Name: count, dtype: int64

Column: Cyl
Cyl
(6 cyl)     864
(4 cyl)     600
(8 cyl)     533
(5 cyl)     113
(12 cyl)     60
(10 cyl)     29
(2 cyl)       4
(16 cyl)      2
Name: count, dtype: int64

Column: Trans
Trans
Auto-L4    502
Auto-L5    329
Auto-S6    327
Man-6      295
Man-5      269
Auto-S5    147
Auto-L6    118
Auto-AV     86
Auto-S4     42
Auto-L7     42
Auto-S7     22
Auto-4      10
Auto-6       8
S8           8
Name: count, dtype: int64

Column: Drive
Drive
2WD    1525
4WD     786
Name: count, dtype: int64

Column: Fuel
Fuel
Gasoline       2318
ethanol/gas      72
diesel           11
CNG               2
ethanol           1
Name: count, dtype: int64

Column: Sales Area
Sales Area
FA    1157
CA    1084
FC     163
Name: count, dtype: int64

Column: Stnd
Stnd
B5      990
L2      556
U2      428
B4      125
B8       95
HDV      84
S2       76
B2       16
B3       15
SLEV     11
B10       6
LEV       2
Name: count, dtype: int64

Column: Underhood ID
Underhood ID
8GMXK06.0389    48
8BMXB03.0N52    46
8GMXT05.3384    46
8VVXV02.5U2T    32
8BMXV03.0N54    32
                ..
8GMXT02.4135     1
8TYXV02.4HX2     1
8FMXT05.44E2     1
8DSXV02.4GRG     1
8MBXV03.0BN8     1
Name: count, Length: 343, dtype: int64

Column: Veh Class
Veh Class
small car          692
SUV                648
pickup             350
midsize car        276
large car          129
van                129
station wagon      123
minivan             37
special purpose     20
Name: count, dtype: int64

Column: Air Pollution Score
Air Pollution Score
6      1471
7       521
2       112
3        85
9.5      80
6/6      32
3/3      27
9        23
1        22
8        15
7/7      12
0         3
6/4       1
Name: count, dtype: int64

Column: FE Calc Appr
FE Calc Appr
Drv    2175
5cy      30
Name: count, dtype: int64

Column: City MPG
City MPG
17       233
16       216
15       213
20       195
19       182
18       180
14       172
13       160
12       135
21       122
22        88
23        45
24        42
11        35
10        28
11/14     20
26        16
27        16
25        16
9         12
9/12      10
29        10
9/14       9
9/13       7
8          6
11/15      6
34         6
13/18      4
28         4
10/13      3
33         2
40         2
48         2
10/14      2
13/19      2
11/17      1
35         1
12/16      1
14/18      1
Name: count, dtype: int64

Column: Hwy MPG
Hwy MPG
24       241
20       174
25       169
26       167
28       148
19       144
22       143
18       126
27       123
23       106
29        99
17        99
31        76
30        66
16        59
21        58
32        35
33        34
15        21
14/19     14
34        12
15/20     12
35        11
14        10
12/17      8
12/19      7
12/16      6
13         6
36         6
45         4
13/18      2
13/17      2
19/25      2
13/19      2
12/18      2
16/23      2
20/27      2
37         2
17/24      1
19/26      1
17/23      1
20/28      1
21/29      1
Name: count, dtype: int64

Column: Cmb MPG
Cmb MPG
20       215
22       211
19       196
18       183
21       166
15       164
14       156
16       144
17       139
24       134
23       119
25        73
26        46
13        34
27        34
12        30
28        28
29        24
12/16     20
10/15     15
11        14
10/14     11
32         8
10         6
31         6
13/17      4
11/15      3
15/21      3
16/22      3
34         3
13/18      2
12/15      2
42         2
30         2
46         2
14/19      1
16/21      1
13/19      1
Name: count, dtype: int64

Column: Unadj Cmb MPG
Unadj Cmb MPG
18.9273    16
13.8612    16
27.7684    14
29.2274    14
28.6009    12
           ..
24.9963     1
24.4810     1
17.6455     1
26.0747     1
25.1000     1
Name: count, Length: 721, dtype: int64

Column: Greenhouse Gas Score
Greenhouse Gas Score
6      589
5      380
7      327
4      285
3      165
2      156
8      131
0       50
1       33
6/4     24
9       19
4/3     15
4/2     11
8/6      4
10       4
5/3      3
7/6      3
6/5      3
6/3      2
7/5      1
Name: count, dtype: int64

Column: SmartWay
SmartWay
no     1766
yes     638
Name: count, dtype: int64

Column: Model.1
Model.1
FORD F350                         48
GMC Sierra 15                     36
CHEVROLET Silverado 15            36
CHEVROLET Colorado                24
FORD F250                         24
                                  ..
ISUZU Ascender                     1
MERCEDES-BENZ CLS550               1
MERCEDES-BENZ CLK550 Cabriolet     1
MERCEDES-BENZ CLK550               1
FORD F150 SFE                      1
Name: count, Length: 473, dtype: int64

Column: Displ.1
Displ.1
2.5    210
2.0    209
2.4    196
3.5    177
3.0    161
5.3    122
3.6    107
6.0    100
4.0     98
3.7     98
3.8     78
5.4     73
4.8     72
4.6     63
4.2     60
1.6     54
5.7     53
1.8     52
6.2     49
2.7     46
2.3     42
2.2     42
4.7     38
6.7     32
2.9     32
3.2     32
5.5     30
6.8     26
5.6     23
5.0     20
2.8     20
4.3     20
4.4     16
3.3     16
3.4     16
1.5     12
6.1     10
5.2     10
5.9      8
6.5      8
3.9      8
1.3      6
8.4      4
4.5      4
1.0      4
3.1      2
7.0      2
Name: count, dtype: int64

Column: Cyl.1
Cyl.1
6.0     843
4.0     761
8.0     559
5.0     114
12.0     52
10.0     26
2.0       4
3.0       4
Name: count, dtype: int64

Column: Trans.1
Trans.1
Auto-S6       414
Auto-L4       407
Man-6         404
Auto-L5       351
Auto-L6       309
Man-5         274
Auto-S5       127
Auto-AV        93
Auto-S7        48
Auto-S4        46
Auto-L7        36
CVT            16
SemiAuto-6     12
Auto-7          8
Auto-6          4
Auto-5          4
AutoMan-5       4
AutoMan-7       2
SemiAuto-7      2
Name: count, dtype: int64

Column: Drive.1
Drive.1
2WD    1714
4WD     847
Name: count, dtype: int64

Column: Fuel.1
Fuel.1
Gasoline       2387
ethanol/gas     141
diesel           30
CNG               2
Ethanol/Gas       1
Name: count, dtype: int64

Column: Sales Area.1
Sales Area.1
FA    1226
CA    1130
FC     205
Name: count, dtype: int64

Column: Stnd.1
Stnd.1
B5     1114
L2      524
U2      488
B4      171
S2      112
HDV      82
B2       24
B8       21
B3       13
Mod      12
Name: count, dtype: int64

Column: Stnd Description
Stnd Description
Bin 5                      1072
LEV-II LEV                  510
LEV-II ULEV                 464
Bin 4                       171
LEV-II SULEV                109
HEAVY DUTY                   82
Federal Tier 2 Bin 5         42
Bin 2                        24
California LEV-II ULEV       24
Bin 8                        21
California LEV-II LEV        14
Bin 3                        13
Modified (Mod)               12
California LEV-II SULEV       3
Name: count, dtype: int64

Column: Underhood ID.1
Underhood ID.1
9GMXD06.0396    64
9BMXB03.0N5R    48
9GMXT05.3384    47
9ADXV02.03UA    40
9PRXV03.8CDI    40
                ..
9GMXT02.4130     1
9GMXV03.9054     1
9NSXV02.5G3A     1
9GMXT03.6150     1
9CRXV02.4CR0     1
Name: count, Length: 361, dtype: int64

Column: Veh Class.1
Veh Class.1
small car          812
SUV                669
pickup             360
midsize car        267
station wagon      174
large car          134
van                 80
special purpose     33
minivan             32
Name: count, dtype: int64

Column: Air Pollution Score.1
Air Pollution Score.1
6      1513
7       576
2       116
9.5     104
6/6      69
7/7      55
9        32
1        28
3        25
3/3      16
8        13
Mod      12
6/4       2
Name: count, dtype: int64

Column: City MPG.1
City MPG.1
17       300
18       232
16       220
15       206
14       204
20       177
19       160
21       136
13       101
22       100
12        63
11        56
23        54
25        46
24        40
26        37
10/14     33
27        26
10        18
29        18
9/12      15
28        12
10/12     10
9/13      10
9/14      10
11/15      8
16/22      8
9          8
34         6
33         6
13/17      6
10/13      4
16/21      4
15/22      4
8          4
11/14      4
12/16      3
13/18      2
14/19      2
40         2
11/17      2
13/19      2
48         2
12/18      1
35         1
Name: count, dtype: int64

Column: Hwy MPG.1
Hwy MPG.1
25       215
24       196
26       194
20       188
28       165
23       155
27       146
19       128
22       120
29       103
18        99
30        82
21        73
17        56
31        53
34        47
33        44
32        44
16        34
14/19     30
35        27
15/20     26
37        16
15        16
14        10
13/19      8
36         8
22/30      8
16/21      8
13/18      6
14/20      5
19/25      4
13         4
39         4
12/18      4
20/27      4
41         4
21/29      4
23/32      4
12/16      4
45         4
17/24      3
20/26      2
12/19      2
22/29      2
16/24      2
19/26      1
12/17      1
Name: count, dtype: int64

Column: Cmb MPG.1
Cmb MPG.1
20       287
21       226
18       200
19       185
16       183
22       167
23       132
17       122
24       119
15       118
25        98
14        82
29        51
26        46
28        43
13        42
27        35
12/16     28
30        28
32        22
12        18
11/15     17
11/14     14
10/15     14
11        12
13/17      8
15/21      7
10/14      6
19/26      4
31         4
19/24      4
36         4
13/16      4
18/25      4
10         4
17/24      4
34         3
14/19      3
11/16      3
42         2
13/19      2
15/20      2
16/22      2
17/23      2
46         2
Name: count, dtype: int64

Column: Greenhouse Gas Score.1
Greenhouse Gas Score.1
5      509
4      385
3      305
6      299
7      298
8      124
2      118
1       82
0       76
3/3     28
9       23
2/2     17
7/7     16
2/1     14
1/2     14
Mod     12
4/3     12
5/5      9
1/1      6
10       4
5/4      3
2/3      3
7/6      2
6/6      2
4/4      2
Name: count, dtype: int64

Column: SmartWay.1
SmartWay.1
no     1956
yes     605
Name: count, dtype: int64

Column: Model.2
Model.2
FORD F350                  48
FORD F250                  24
TOYOTA Tacoma              18
VOLKSWAGEN Jetta           18
DODGE RAM 2500             16
                           ..
TOYOTA Sequoia FFV          1
MERCEDES-BENZ CLS550        1
FORD Transit Connect        1
FORD Crown Victoria FFV     1
NISSAN Armada FFV           1
Name: count, Length: 495, dtype: int64

Column: Displ.2
Displ.2
2.0    224
3.0    219
2.4    218
2.5    197
3.5    179
4.0     94
3.6     94
3.8     80
5.4     76
3.7     73
4.6     62
1.6     56
6.0     55
5.0     48
2.2     48
5.7     45
4.8     40
2.7     39
1.8     38
5.3     33
3.2     31
6.8     30
5.5     28
6.2     25
6.7     24
4.4     24
4.2     22
2.9     20
2.3     18
5.6     18
4.3     16
4.7     16
5.2     14
5.9     14
1.3     12
3.3     12
6.3     12
1.5     10
6.5     10
6.1     10
3.4      8
4.5      6
3.9      6
2.8      4
8.4      4
1.0      4
8.0      2
7.0      2
6.6      2
Name: count, dtype: int64

Column: Cyl.2
Cyl.2
6.0     835
4.0     779
8.0     502
5.0      78
12.0     62
10.0     56
2.0       4
3.0       4
16.0      2
Name: count, dtype: int64

Column: Trans.2
Trans.2
SemiAuto-6    463
Man-6         410
Auto-5        283
Auto-4        242
Auto-6        220
Man-5         213
CVT           113
Auto-7        111
SemiAuto-5     99
SemiAuto-7     44
Other-1        41
SemiAuto-4     29
AutoMan-6      28
SemiAuto-8     22
AutoMan-7       4
AutoMan-5       4
Name: count, dtype: int64

Column: Drive.2
Drive.2
2WD    1577
4WD     749
Name: count, dtype: int64

Column: Fuel.2
Fuel.2
Gasoline       2123
Ethanol/Gas     137
Diesel           58
Hydrogen          4
Ethanol           2
CNG               2
Name: count, dtype: int64

Column: Sales Area.2
Sales Area.2
FA    1110
CA    1033
FC     183
Name: count, dtype: int64

Column: Stnd.2
Stnd.2
B5      972
U2      498
L2      364
B4      172
S2      129
B3       42
HDV1     40
Mod      38
B8       31
HDV2     16
L2OP     14
B2        6
B1        2
ZEV       2
Name: count, dtype: int64

Column: Stnd Description.1
Stnd Description.1
Federal Tier 2 Bin 5                972
California LEV-II ULEV              498
California LEV-II LEV               364
Federal Tier 2 Bin 4                172
California LEV-II SULEV             129
Federal Tier 2 Bin 3                 42
Federal HDV (8500-10,000 GVWR)       40
Modified (Mod)                       38
Federal Tier 2 Bin 8                 31
Federal HDV (10,001-14,000 GVWR)     16
California LEV-II LEV Optional       14
Federal Tier 2 Bin 2                  6
Federal Tier 2 Bin 1                  2
California ZEV                        2
Name: count, dtype: int64

Column: Underhood ID.2
Underhood ID.2
ABMXJ03.0E89    52
APRXV03.8CDI    40
AGMXV02.4027    32
AGMXT05.3373    29
ABMXV03.051R    28
                ..
AGMXT02.4135     1
ATKXV02.5NC2     1
ADSXV02.4G6G     1
AHYXV02.0HPC     1
AKMXV02.4DPC     1
Name: count, Length: 359, dtype: int64

Column: Veh Class.2
Veh Class.2
small car          820
SUV                566
midsize car        283
pickup             241
station wagon      161
large car          129
van                 58
special purpose     37
minivan             31
Name: count, dtype: int64

Column: Air Pollution Score.2
Air Pollution Score.2
6      1253
7       599
9.5     102
6/6      64
2        64
7/7      46
8        42
Mod      38
9        33
3        30
3/3      25
1        24
10        4
6/4       2
Name: count, dtype: int64

Column: City MPG.2
City MPG.2
18       262
17       236
16       189
21       155
15       147
19       138
22       129
20       128
14       110
23        87
13        72
12        63
25        61
11        54
24        48
26        40
27        25
29        18
10/13     15
11/15     15
28        14
10        14
9         12
9/12      11
10/14     11
9/13       9
13/18      8
30         8
40         8
16/22      8
14/19      7
9/14       7
34         6
8          6
33         6
15/22      5
41         4
12/16      3
35         3
32         2
13/17      2
60         2
13/19      2
12/17      2
51         2
14/18      1
Name: count, dtype: int64

Column: Hwy MPG.2
Hwy MPG.2
25       205
27       179
26       166
23       131
28       130
24       122
20       113
22       112
31       103
29       100
30        95
19        91
21        79
18        79
17        56
32        52
34        49
33        49
35        31
36        25
37        22
15        16
16/21     11
16        10
14/19      9
13/17      9
13/18      9
14         8
43         6
39         6
12/17      5
17/24      5
20/27      5
19/25      5
13/19      5
41         4
13         4
13/20      4
22/30      4
16/22      4
19/26      3
23/33      3
22/29      3
16/20      3
23/32      2
23/30      2
12/18      2
14/20      2
45         2
60         2
12/16      2
15/20      2
21/30      2
48         2
18/25      2
12/19      1
20/26      1
17/23      1
Name: count, dtype: int64

Column: Cmb MPG.2
Cmb MPG.2
21       209
20       208
22       191
19       166
18       155
25       136
24       121
23       110
17       106
16       103
15        83
26        73
14        69
29        60
28        49
27        44
13        34
30        33
32        24
12        22
11/14     15
31        12
13/17     11
11/15     11
11        10
12/16      9
10/14      8
15/21      6
10         6
41         6
11/16      4
10/15      4
16/22      4
13/18      4
18/25      4
36         4
15/20      4
39         4
18/26      3
34         3
14/19      3
16/21      3
35         2
42         2
60         2
50         2
13/19      2
17/23      2
19/25      2
17/25      2
19/26      2
12/15      2
17/22      1
Name: count, dtype: int64

Column: Greenhouse Gas Score.2
Greenhouse Gas Score.2
5      415
7      372
4      323
6      301
3      209
8      152
2       83
0       70
1       69
9       21
10      18
Mod     18
2/1     15
7/7     13
4/3     11
2/2     11
5/5     10
3/3      9
1/1      8
4/4      6
6/6      4
1/2      4
2/3      4
7/6      3
5/4      3
6/5      3
3/2      2
Name: count, dtype: int64

Column: SmartWay.2
SmartWay.2
no     1610
yes     716
Name: count, dtype: int64

Column: Model.3
Model.3
TOYOTA Tacoma               20
BMW 328Ci                   16
BMW 328i                    16
NISSAN Frontier             16
DODGE RAM 2500              16
                            ..
FORD Transit Connect         1
TOYOTA Sequoia FFV           1
CADILLAC Escalade EXT        1
FORD Mustang Convertible     1
GMC Yukon 1500 Hybrid        1
Name: count, Length: 507, dtype: int64

Column: Displ.3
Displ.3
 3.0    226
 3.5    199
 2.0    199
 2.4    190
 2.5    165
 3.6     94
 3.8     78
 4.0     76
 1.6     75
 3.7     72
 6.0     60
 5.7     53
 6.7     50
 4.6     44
 6.2     43
 1.8     43
 4.4     42
 5.0     41
 5.3     32
 5.5     28
 5.4     28
 3.2     25
 2.7     24
 4.2     24
 5.6     22
 4.7     22
 2.9     20
 6.6     18
 5.2     18
 1.5     18
 4.8     16
 2.3     14
 1.3     14
 3.4     12
 5.9     12
 4.3     12
-1.0     11
 6.3      6
 2.8      6
 6.8      6
 2.2      5
 1.4      4
 1.0      4
 6.4      4
 3.3      2
 3.9      2
 4.5      2
 7.0      2
 8.0      2
Name: count, dtype: int64

Column: Cyl.3
Cyl.3
6.0     816
4.0     719
8.0     503
12.0     44
5.0      40
10.0     22
2.0       4
3.0       4
16.0      2
Name: count, dtype: int64

Column: Trans.3
Trans.3
SemiAuto-6    464
Man-6         372
Auto-6        292
Auto-5        193
Auto-4        152
Man-5         144
Auto-7        133
CVT           115
SemiAuto-8     76
SemiAuto-5     61
SemiAuto-7     60
Other-1        42
AutoMan-6      26
SemiAuto-4     17
Auto-1          8
Auto-8          8
AutoMan-7       4
AutoMan-5       4
Name: count, dtype: int64

Column: Drive.3
Drive.3
2WD    1453
4WD     718
Name: count, dtype: int64

Column: Fuel.3
Fuel.3
Gasoline                1866
Ethanol/Gas              180
Diesel                   103
Electricity               11
Hydrogen                   6
CNG                        4
Electricity/Gasoline       1
Name: count, dtype: int64

Column: Sales Area.3
Sales Area.3
FA    1006
CA     926
FC     239
Name: count, dtype: int64

Column: Stnd.3
Stnd.3
B5      894
U2      511
L2      259
B4      197
S2      111
B8       48
Mod      38
B3       35
HDV1     20
HDV2     16
L2OP     14
B2       11
B1        9
ZEV       8
Name: count, dtype: int64

Column: Stnd Description.2
Stnd Description.2
Federal Tier 2 Bin 5                894
California LEV-II ULEV              511
California LEV-II LEV               259
Federal Tier 2 Bin 4                197
California LEV-II SULEV             111
Federal Tier 2 Bin 8                 48
Modified (Mod)                       38
Federal Tier 2 Bin 3                 35
Federal HDV (8500-10,000 GVWR)       20
Federal HDV (10,001-14,000 GVWR)     16
California LEV-II LEV Optional       14
Federal Tier 2 Bin 2                 11
Federal Tier 2 Bin 1                  9
California ZEV                        8
Name: count, dtype: int64

Column: Underhood ID.3
Underhood ID.3
BPRXV03.8CDI    50

# New Section